name: Emage
version: ${project.version}
main: net.edithymaster.emage.EmagePlugin
description: Renders static images and GIFs to item frames with accurate colors and dithering.
api-version: '1.18'
authors: [EdithyMaster]

commands:
  emage:
    description: Apply a static image or GIF to Item Frames
    permission: emage.use

permissions:
  emage.use:
    default: true
  emage.admin:
    default: op